# Generated by Django 4.1 on 2022-08-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_content', '0002_rename_rank_course_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.CharField(max_length=300),
        ),
    ]
